name: Maven CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.failure.ignore=true

      - name: Generate Cucumber Report
        run: mvn verify -Dmaven.test.failure.ignore=true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/
