name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Cucumber Tests
        run: mvn test

      # Fail-proof HTML report generation
      - name: Generate Cucumber Report
        run: |
          if [ -f target/cucumber.json ]; then
            mvn net.masterthought:maven-cucumber-reporting:5.7.5:generate
          else
            echo "JSON report missing, skipping HTML report generation"
          fi
        continue-on-error: true

      # Upload HTML report if exists
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-report

      # Upload JSON report if exists
      - name: Upload JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber.json
