name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Maven Dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build Project without tests
      - name: Build Project
        run: mvn clean install -DskipTests

      # 5️⃣ Run Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn test

      # 6️⃣ Generate Cucumber Report (fail-safe)
      - name: Generate Cucumber Report
        run: mvn verify || echo "Report generation failed, but continuing..."
        continue-on-error: true

      # 7️⃣ Upload HTML Report if exists
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-report

      # 8️⃣ Upload JSON Report if exists
      - name: Upload JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber.json
