name: Maven CI/CD Pipeline

on:
  workflow_dispatch:   # manual trigger
  # you can also add push / pull_request if needed
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies & build
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run tests
      - name: Run Tests
        run: mvn test

      # Generate Cucumber HTML Reports
      - name: Generate Reports
        run: mvn verify

      # Upload Test Reports as artifacts
      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-reports
          path: target/HTML-reports

      - name: Upload Cucumber JSON
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json
          path: target/cucumber.json
