name: Maven CI with Cucumber Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven (run tests + generate reports)
        run: mvn clean verify -Dmaven.test.failure.ignore=false

      - name: Archive cucumber reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/cucumber-html-reports/
